### ISSUE TITLE
Tarang has missing dependency issue on Node  < 17 

### ISSUE THREAD

**Issue by sudarshansb143** [kamalyesh/tarang#1]
Tarang has missing dependencies for node version less than 17.

After installing tarang I got this 

```
./node_modules/tarang/dist/index.modern.js
Module not found: Can't resolve 'd3' in 'D:\project1\node_modules\tarang\dist'
```

My node version is :  14.0.2

**Comment by kamalyesh** [comment]
Thanks for reporting the issue.
I will check what can be done about it.

**Comment by kamalyesh** [comment]
It looks like this occurred because of peerDependency.

As stated in this [blog](https://nodejs.org/es/blog/npm/peer-dependencies/), if you have npm version 1, 2 or 7, these peer dependencies will be automatically installed and the issue will not occur.

**Comment by sudarshansb143** [comment]
yeah ! 

after som  googling I have installed NVM and switched to the latest version of Node.js (17.2). by doing this I am able to get it done.
